version: "3.9"
services:
  db:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: project
    ports:
      - "5432:5432"
    volumes:
      - ./postgresDB:/var/lib/postgres/data
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:3000"
    depends_on:
      - db
